trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'azure-wms-connection'
  webAppName: 'wms-sql-chaitanya09'

steps:

- checkout: self
  clean: true

- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: sdk
    version: '8.0.x'

- script: |
    dir
    dotnet restore WMS-Solution.slnx
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build WMS-Solution.slnx --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'

- script: |
    dotnet test WMS.Tests/WMS.Tests.csproj --configuration $(buildConfiguration) --no-build
  displayName: 'Run Unit Tests'

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'WMS.API/WMS.API.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy API to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/publish/*.zip'