trigger:
  branches:
    include:
      - dev

  paths:
    include:
      - WMS.Frontend/*
      - WMS.Frontend/**
    exclude:
      - WMS.API/*
      - WMS.API/**
      - WMS.Tests/*
      - WMS.Tests/**
      - WMS-Solution.sln

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build_and_deploy
  displayName: Build and Deploy Angular App

  steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '22.x'

  - script: |
      echo "--- Checking Node Version ---"
      node -v
      npm -v
      echo "-----------------------------"

      cd WMS.Frontend

      npm install
      npm run build -- --configuration production
    displayName: 'Install dependencies and build Angular'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web Apps'
    inputs:
      app_location: 'WMS.Frontend'
      api_location: ''
      output_location: 'WMS.Frontend/dist/WMS.Frontend/browser'
      skip_app_build: true
      azure_static_web_apps_api_token: 'b492e8a407db1600d45d5a66c7d8eed66f9b171200f4f593297df7e8d675cfee07-e4bc98da-9e15-4ac4-a222-328b357a05b000007060ca652800'