trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - WMS.Frontend/*
      - WMS.Frontend/**
    exclude:
      - WMS.API/*
      - WMS.API/**
      - WMS.Tests/*
      - WMS.Tests/**
      - WMS-Solution.sln

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build_and_deploy
  displayName: Build and Deploy Angular App

  steps:
  - checkout: self
    clean: true

  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '20.x'

  - script: |
      cd WMS.Frontend
      npm ci
      npm run build -- --configuration production
    displayName: 'Install dependencies and build Angular'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web Apps'
    inputs:
      app_location: 'WMS.Frontend/dist/wms-frontend/browser'
      api_location: ''
      output_location: ''
      skip_app_build: true
      azure_static_web_apps_api_token: '6ac1178e2c7b645834602f6aa691d145f832ea358ab09efa6e3099eb4059717107-cb47aa6a-a337-4ceb-a68a-eec938cad62b00007060ca652800'